# Generated by Django 2.0.6 on 2018-07-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddressBookApp', '0002_auto_20180726_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbookapplication',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addressbookapplication',
            name='email_address',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='addressbookapplication',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addressbookapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='addressbookapplication',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='addressbookapplication',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addressbookapplication',
            name='zip_code',
            field=models.IntegerField(max_length=10),
        ),
    ]
